[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi_call = { path = "../crates/sbi_call" }
print = { path = "../crates/print" }
panic = { path = "../crates/panic" }
entry = { path = "../crates/entry" }
